import os
from dotenv import load_dotenv

load_dotenv()

# Azure Configuration
ENDPOINT = os.getenv("AZURE_AI_PROJECT_ENDPOINT")
RESOURCE_GROUP = os.getenv("AZURE_AI_RESOURCE_GROUP")
SUBSCRIPTION_ID = os.getenv("AZURE_SUBSCRIPTION_ID")
PROJECT_NAME = os.getenv("AZURE_PROJECT_NAME")

# Azure OpenAI Configuration
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")

# Cosmos DB Configuration
COSMOS_DB_ENDPOINT = os.getenv("COSMOS_DB_ENDPOINT")
COSMOS_DB_KEY = os.getenv("COSMOS_DB_KEY")
COSMOS_DB_DATABASE_NAME = os.getenv("COSMOS_DB_DATABASE_NAME", "DB")
COSMOS_DB_CONTAINER_NAME = os.getenv("COSMOS_DB_CONTAINER_NAME", "data")

# Customer ID Configuration
DEFAULT_CUSTOMER_ID_PREFIX = os.getenv("DEFAULT_CUSTOMER_ID_PREFIX", "CUST")

# Agent Index Configuration
IDENTITY_INDEX = os.getenv("IDENTITY_INDEX")
INCOME_INDEX = os.getenv("INCOME_INDEX")
GUARANTOR_INDEX = os.getenv("GUARANTOR_INDEX")
INSPECTION_INDEX = os.getenv("INSPECTION_INDEX")
VALUATION_INDEX = os.getenv("VALUATION_INDEX")
